### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by dsm-72** [Inqling/svelte-icons#6]
In svelte kit

```jsx
<script>
import {BrandGithub} from '@inqling/svelte-icons/brand';
</script>

<BrandGithub />
```

and 

> Cannot read properties of undefined (reading 'BrandGithub')

**Comment by OllieJT** [comment]
Hi @dsm-72,

I typically import icons via their full path, however both should work.
```html
<script>
	import { BrandGithub } from '@inqling/svelte-icons/brand';
	import GitHub from '@inqling/svelte-icons/brand/github.svelte';
</script>

<GitHub />

<BrandGithub />
```

Could you confirm what version of `svelte` and `@inqling/svelte-icons` you're running?

Could you also check for me if importing via the full path works for you? This would still need to be fixed, but will help in debugging the issue.

Here are the versions I am running, for convenience:
```json
{
	"@inqling/svelte-icons": "^2.4.0",
	"@sveltejs/kit": "^1.0.13",
	"svelte": "^3.55.1",
	"tslib": "^2.4.1",
	"typescript": "^4.9.4",
	"vite": "^4.0.4",
}
```

**Comment by OllieJT** [comment]
@dsm-72 Just checking in to see if you resolved this issue or of you need help. 

As I can't replicate it, I will close this issue on Sunday unless I hear from you by then

**Comment by dsm-72** [comment]
I still can't get it to work. I just made my own components for the icons I needed for now.

**Comment by OllieJT** [comment]
Happy to help if you would like to trouleshoot with me. Closing for now until then. 👍
